/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harj.monivalinta;

public class Gui extends javax.swing.JFrame {

    static void start() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Gui
     */
    public Gui() {
        Controlleri c = new Controlleri();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jInfo = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        mLoginMenu = new javax.swing.JMenu();
        mUusiUser = new javax.swing.JMenuItem();
        mLogin = new javax.swing.JMenuItem();
        mOpettaja = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenuItem();
        mMateriaaliMenu = new javax.swing.JMenu();
        mAvaaMatsku = new javax.swing.JMenuItem();
        mAloitaKoe = new javax.swing.JMenuItem();
        mTutkiTuloksia = new javax.swing.JMenuItem();
        mTeeMatsku = new javax.swing.JMenuItem();
        mOhjeMenu = new javax.swing.JMenu();
        mOhjeita = new javax.swing.JMenuItem();
        mAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInfo.setText(" ");

        mLoginMenu.setMnemonic('K');
        mLoginMenu.setText("Kirjautuminen");

        mUusiUser.setMnemonic('U');
        mUusiUser.setText("Uusi käyttäjä");
        mUusiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUusiUserActionPerformed(evt);
            }
        });
        mLoginMenu.add(mUusiUser);

        mLogin.setMnemonic('L');
        mLogin.setText("Login");
        mLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginActionPerformed(evt);
            }
        });
        mLoginMenu.add(mLogin);

        mOpettaja.setMnemonic('O');
        mOpettaja.setText("Opettaja");
        mOpettaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOpettajaActionPerformed(evt);
            }
        });
        mLoginMenu.add(mOpettaja);

        mExit.setMnemonic('x');
        mExit.setText("Exit");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        mLoginMenu.add(mExit);

        menuBar.add(mLoginMenu);

        mMateriaaliMenu.setMnemonic('M');
        mMateriaaliMenu.setText("Materiaali");

        mAvaaMatsku.setMnemonic('t');
        mAvaaMatsku.setText("Avaa materiaali");
        mAvaaMatsku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAvaaMatskuActionPerformed(evt);
            }
        });
        mMateriaaliMenu.add(mAvaaMatsku);

        mAloitaKoe.setMnemonic('p');
        mAloitaKoe.setText("Aloita koe");
        mAloitaKoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAloitaKoeActionPerformed(evt);
            }
        });
        mMateriaaliMenu.add(mAloitaKoe);

        mTutkiTuloksia.setMnemonic('y');
        mTutkiTuloksia.setText("Tarkastele tuloksia");
        mTutkiTuloksia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTutkiTuloksiaActionPerformed(evt);
            }
        });
        mMateriaaliMenu.add(mTutkiTuloksia);

        mTeeMatsku.setMnemonic('d');
        mTeeMatsku.setText("Tee uusi materiaali");
        mTeeMatsku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTeeMatskuActionPerformed(evt);
            }
        });
        mMateriaaliMenu.add(mTeeMatsku);

        menuBar.add(mMateriaaliMenu);

        mOhjeMenu.setMnemonic('O');
        mOhjeMenu.setText("Ohjeita");

        mOhjeita.setMnemonic('c');
        mOhjeita.setText("Ohjeita");
        mOhjeita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOhjeitaActionPerformed(evt);
            }
        });
        mOhjeMenu.add(mOhjeita);

        mAbout.setMnemonic('a');
        mAbout.setText("Tietoja ohjelmasta");
        mAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAboutActionPerformed(evt);
            }
        });
        mOhjeMenu.add(mAbout);

        menuBar.add(mOhjeMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jInfo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        jInfo.setText("mExitActionPerformed");
        System.exit(0);
    }//GEN-LAST:event_mExitActionPerformed

    private void mLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoginActionPerformed
        jInfo.setText("mLoginActionPerformed");
    }//GEN-LAST:event_mLoginActionPerformed

    private void mUusiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUusiUserActionPerformed
        jInfo.setText("mUusiUserActionPerformed");
    }//GEN-LAST:event_mUusiUserActionPerformed

    private void mOpettajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOpettajaActionPerformed
       jInfo.setText("mOpettajaActionPerformed");
    }//GEN-LAST:event_mOpettajaActionPerformed

    private void mAvaaMatskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAvaaMatskuActionPerformed
       jInfo.setText("mMatskuActionPerformed");
    }//GEN-LAST:event_mAvaaMatskuActionPerformed

    private void mAloitaKoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAloitaKoeActionPerformed
        jInfo.setText("mAloitaKoeActionPerformed");
    }//GEN-LAST:event_mAloitaKoeActionPerformed

    private void mTutkiTuloksiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTutkiTuloksiaActionPerformed
jInfo.setText("mTutkiTuloksiaActionPerformed");
    }//GEN-LAST:event_mTutkiTuloksiaActionPerformed

    private void mTeeMatskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTeeMatskuActionPerformed
     jInfo.setText("mTeeUusiMatskuActionPerformed");
    }//GEN-LAST:event_mTeeMatskuActionPerformed

    private void mOhjeitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOhjeitaActionPerformed
       jInfo.setText("mOhjeitaActionPerformed");
    }//GEN-LAST:event_mOhjeitaActionPerformed

    private void mAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAboutActionPerformed
      jInfo.setText("mAboutActionPerformed");
    }//GEN-LAST:event_mAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Gui().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JTextField jInfo;
    private javax.swing.JMenuItem mAbout;
    private javax.swing.JMenuItem mAloitaKoe;
    private javax.swing.JMenuItem mAvaaMatsku;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenuItem mLogin;
    private javax.swing.JMenu mLoginMenu;
    private javax.swing.JMenu mMateriaaliMenu;
    private javax.swing.JMenu mOhjeMenu;
    private javax.swing.JMenuItem mOhjeita;
    private javax.swing.JMenuItem mOpettaja;
    private javax.swing.JMenuItem mTeeMatsku;
    private javax.swing.JMenuItem mTutkiTuloksia;
    private javax.swing.JMenuItem mUusiUser;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
    private Controlleri c;

}
